# Generated by Django 2.0.2 on 2018-02-25 13:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_created=True)),
                ('query', models.CharField(max_length=32)),
                ('stopped', models.DateTimeField(blank=True, help_text='Defaults to start + 24hours', null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('allow_consumption', models.BooleanField(default=True, help_text='Should incoming tweets actually be consumed or just left in the queue?')),
                ('allow_search', models.BooleanField(default=False)),
                ('last_distilled', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Disabled')], default=1)),
                ('cloud', models.TextField(blank=True)),
                ('statistics', models.TextField(blank=True)),
                ('images', models.TextField(blank=True)),
                ('cloud_generated', models.DateTimeField(blank=True, null=True)),
                ('map_generated', models.DateTimeField(blank=True, null=True)),
                ('search_generated', models.DateTimeField(blank=True, null=True)),
                ('statistics_generated', models.DateTimeField(blank=True, null=True)),
                ('images_generated', models.DateTimeField(blank=True, null=True)),
                ('colour_overrides', models.TextField(blank=True, help_text='A JSON field used to override the colours used by c3 in generating pie charts.')),
                ('total', models.BigIntegerField(default=0)),
                ('size', models.BigIntegerField(default=0, help_text='The size, in bytes, of the tweets field')),
            ],
            options={
                'ordering': ('-started',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('label', models.CharField(max_length=64)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='archive.Archive')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True)),
                ('mentions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), blank=True, null=True, size=None)),
                ('text', models.CharField(db_index=True, max_length=256)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='archive.Archive')),
            ],
        ),
    ]
