# Generated by Django 2.0.2 on 2018-02-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archives', to=settings.AUTH_USER_MODEL),
        ),
    ]
