#!/usr/bin/env bash

while ! echo "SELECT * FROM socialaccount_socialapp LIMIT 1" | psql -U postgres -h postgres 2> /dev/null | grep twitter; do
  echo "Waiting for PostgreSQL"
  sleep 1
done

celery -A albatross worker -l info --workdir=/app/src/

