#!/usr/bin/env sh

while ! echo "SELECT * FROM socialaccount_socialapp LIMIT 1" | psql -U postgres -h postgres 2> /dev/null | grep twitter; do
  echo "Waiting for PostgreSQL"
  sleep 1
done

for line in $(grep VERBOSITY /app/.env); do
  export ${line}
done

sleep 3

/app/src/manage.py collector --verbosity ${VERBOSITY:-1}
