#!/usr/bin/env sh

while ! echo "SELECT * FROM socialaccount_socialapp LIMIT 1" | psql -U postgres -h postgres 2> /dev/null | grep twitter; do
  echo "Waiting for PostgreSQL"
  sleep 1
done

sleep 5

# Migrate on every start regardless
/app/src/manage.py collector
