#!/usr/bin/env sh

while ! echo "SELECT * FROM socialaccount_socialapp LIMIT 1" | psql -U postgres -h postgres 2> /dev/null | grep twitter; do
  echo "Waiting for PostgreSQL"
  sleep 1
done

sleep 5

if [[ "${ALBATROSS_IS_PRODUCTION}" = "1" ]]; then
  gunicorn --chdir=/app/src albatross.wsgi:application -c /app/src/albatross/gunicorn.py
else
  /app/src/manage.py runserver 0.0.0.0:8000 --verbosity 3
fi
